### ISSUE TITLE
Request - Example repo using this plugin

### ISSUE THREAD

**Issue by dougmacklin** [njosefbeck/gatsby-plugin-stripe-elements#2]
This is my first time working with the Stripe API so I have some learning to do on that end, however I'm wondering if you have a barebones example that uses this gatsby plugin and combines it with  [react-stripe-elements](https://github.com/stripe/react-stripe-elements). I'm a little confused about a few things:

1. Do I still need to also install `react-stripe-elements`?
2. Should I pretty much follow along with the `react-stripe-elements` [getting started documentation](https://github.com/stripe/react-stripe-elements#getting-started) or are there other things to consider when integrating with Gatsby
3. If I only want to add `stripe.js` on a single page, should I not be using this plugin?

Thanks in advance!

**Comment by njosefbeck** [comment]
Hi Doug! Thanks for the request. I'll try to answer your questions as best as I can. This plugin is actually rather simple, in that all it does is inject https://js.stripe.com/v3/ into every page of your Gatsby site.

Also, according to Stripe, it's important to include this script on every page of your site. They say:

> To best leverage Stripe’s advanced fraud functionality, include this script on every page on your site, not just the checkout page. Including the script on every page allows Stripe to detect anomalous behavior that may be indicative of fraud as users browse your website.
https://stripe.com/docs/stripe-js/elements/quickstart

By using this plugin, you already have [this step done](https://github.com/stripe/react-stripe-elements#then-load-stripejs-in-your-application) from the react-stripe-elements documentation.

I unfortunately don't have an example Gatsby application for this plugin, but I would be happy to link to one in the repo if you happen to create one. If you run into issues along the way, feel free to reach out and maybe I can help!

**Comment by dougmacklin** [comment]
Gotcha, that clears a lot up for me! Thanks @njosefbeck
