### ISSUE TITLE
Allow whitelisting routes

### ISSUE THREAD

**Issue by brimtown** [njosefbeck/gatsby-plugin-stripe-elements#4]
Hi!

[Stripe's docs](https://stripe.com/docs/stripe-js/reference#including-stripejs) recommend loading their snippet on every page, but that seems intended for users of their Radar product. Whitelisting the snippet to routes that actually use Stripe Elements would eliminate the need to load this file for users on other pages of a Gatsby site.

Would you be open to this plugin including a `routes` option, which would limit the inclusion of the snippet to a set of whitelisted routes?

Happy to send a patch over myself, but wanted to gauge your interest in the feature first.

Thanks for creating this plugin!

**Comment by njosefbeck** [comment]
👋🏻 Hi @brimtown!

So, after doing some research, it seems like Radar is an important part of detecting whether or not a Stripe payment is likely to be fraudulent. It seems to do this without a user having to opt into the main pieces of functionality, and according to their documentation, for Radar to most accurately assess whether a transaction is fraudulent or not, the Stripe script must be included on every page ([Radar Integration Checklist](https://stripe.com/docs/radar/checklist)).

Now, that being said, if a developer feels like the performance gains of not including the Stripe script on every page outweighs the fraud detection, then having your feature would be great! We would just need to make sure that those using the feature were aware of Stripe's recommendation, and provide links to Radar's documentation so they can make an informed decision. 

Feel free to update the README to include your feature when creating your PR. I look forward to reviewing it! And thanks for your interest in my humble little plugin :).

**Comment by brimtown** [comment]
Thanks for the response! When I opened the issue, I was under the impression that my team was not using Radar at all. After reading up, I now realize that some of Radar's features appear to be enabled for all Stripe users, and that "Radar for Fraud Teams" is the additional add-on that not everyone is using.

Since it seems like most people will be getting benefits from Radar, I don't see as much use for the proposed feature. Happy to contribute if you still think it's something worth having, but feel free to close the issue.

Thanks again, and we'll likely be using the plugin soon!
