### ISSUE TITLE
Please improve the Readme

### ISSUE THREAD

**Issue by DavidSabine** [njosefbeck/gatsby-plugin-stripe-elements#5]
Hi,

Given there are a few Stripe plugins, it is difficult (for someone not yet familiar with Stripe's APIs) to know how the plugins overlap.

https://www.gatsbyjs.org/packages/gatsby-plugin-stripe/?=stripe

It would be very helpful if the Readme for each of those plugins would include a sentence like:
>Use this plugin when you need... and do not need...
or
>This plugin is different than `Gatsby-plugin-stripe-______` because...
or
>This plugin extends the functionality of `Gatsby-plugin-stripe-______`

**Comment by njosefbeck** [comment]
Hi @DavidSabine, I appreciate you reaching out. 

I've updated this package's README.md to reflect that this plugin is no longer maintained, and that those who wish to use Stripe Elements should instead use [Gatsby Plugin Stripe](https://www.gatsbyjs.org/packages/gatsby-plugin-stripe). 

I will work on updating the other projects' READMEs as well, though note the Gatsby site doesn't pick up README updates as quickly as they have been edited. I will close this issue and respond to the other one you posted on my other stripe plugin once I've made updates. Thanks again!
