### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by cardiv** [njosefbeck/gatsby-plugin-stripe-elements#6]
Hey,

NPM does not know of the package being unmaintained.

This causes the [Gatsby Plugin Library](https://www.gatsbyjs.org/packages/gatsby-plugin-stripe-elements/?=stripe) to list `gatsby-plugin-stripe-elements` without any information about the plugin status.

Could you publish this plugin a last time to NPM with the new `package.json` – without any keywords so Gatsby removes it from the library?

**Comment by njosefbeck** [comment]
Thanks for bringing this to my attention! Should be taken care of now: https://www.npmjs.com/package/gatsby-plugin-stripe-elements

Let me know if you experience any other issues! Thanks!
